# Generated by Django 4.2.8 on 2023-12-18 18:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
