# Generated by Django 4.2.8 on 2023-12-16 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_addresses_city_alter_addresses_phone_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.addresses'),
            preserve_default=False,
        ),
    ]
