# Generated by Django 4.2.8 on 2023-12-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Fullfield'), (1, 'Unfullfield'), (2, 'Canceled'), (3, 'Refunded')], default=0),
        ),
    ]
